### ISSUE TITLE
Split main.go to subpackages

### ISSUE THREAD

**Issue by ilyaglow** [OJ/gobuster#41]
Hey there!
@OJ what you think about splitting gobuster's single main.go file to subpackages? Won't it make project maintaining, mean adding new features, writing tests and merging things easier? Is there any reason to keep gobuster as one big file?
Thank you for an amazing tool, cheers.

**Comment by OJ** [comment]
Hey @ilyaglow thanks for the question!

When I first wrote this thing, I didn't expect it to have the "success" it's had, to be honest!  As a result, I didn't really put the effort into it at the start to make sure it was clean and well structure. The fact that lots of people are using it, forking it, and submitting PR's to it is really unexpected.

I would certainly be open into splitting out the functionality into more sensible logical chunks and turning it into a well-structured application. I don't see a reason to keep it as a single fail any more, it's just remained so due to laziness :)

**Comment by ilyaglow** [comment]
Gobuster seems really promising, and the go power is huge and feels smooth after GIL-enabled languages mess. Btw hate fat java too :)

Well, I tried to split, but I don't like how [it turned out](https://github.com/ilyaglow/gobuster/tree/multiple-files-split)

**Comment by OJ** [comment]
I think this is basically done now. Thoughts?
