### ISSUE TITLE
So, why exactly does dns mode break internet connection?

### ISSUE THREAD

**Issue by 677230756E64** [OJ/gobuster#509]
Had this happen to me, googled it and apparently it's a thing. Never found an answer though. Anybody got to the bottom of it? Using google DNS as well.

**Comment by firefart** [comment]
if you hammer the google dns with thousands of queries in short time, they might block your ip.
Also on unix it creates a lot of sockets and open files because of golangs dns implementation. You can try building with `CGO_ENABLED=1` in your environment variables so the unix implementation will use the system dns settings

**Comment by 677230756E64** [comment]
How much is too much for google in terms of queries? I used delay 100ms so 10 requests per second which doesn't seem that much to me.
