### ISSUE TITLE
I think I may have found an issue...

### ISSUE THREAD

**Issue by Viss** [OJ/gobuster#8]
Its likely with how you're parsing what's legitimately a real page, what is a 404 and what happens when a site confuses the two. 

www.whoismrrobot.com, for example, doesn't have a 404 - it redirects anything that would be a 404 back to the main page, so you get this as a result: 

```
=====================================================
Gobuster v0.8 (DIR support by OJ Reeves @TheColonial)
              (DNS support by Peleus     @0x42424242)
=====================================================
[+] Mode         : dir
[+] Url/Domain   : http://www.whoismrrobot.com/
[+] Threads      : 10
[+] Wordlist     : list.txt
[+] Status codes : 200,204,301,302,307
=====================================================
/A (200)
/about-us (200)
/aboutus (200)
/acceso (200)
/academics (200)
/abstract (200)
/aboutUs (200)
/about_us (200)
/AboutUs (200)
/About (200)
/accesswatch (200)
/accessories (200)
/action (200)
/accounts (200)
/acciones (200)
/activities (200)
/active (200)
/accessibility (200)
/ad (200)
/adclick (200)
/adlog (200)
/admcgi (200)
/admin-bak (200)
/adm (200)
/admin-old (200)
/admin-console (200)
/admin.back (200)
/add (200)```

**Comment by OJ** [comment]
This isn't a bug/issue. If a site returns 200 for every page then
technically every page is "found", which is why it appears in the results
list.

The only way to sort this case is to match on the content returned, whether
it be size of the page or string searching against the body.

String searching is already logged as a future enhancement
https://github.com/OJ/gobuster/issues/5

Page size output will be added too, and probably will get some kind of
filtering support as well. This is also already logged as a future
enhancement https://github.com/OJ/gobuster/issues/6

**Comment by Viss** [comment]
I'm a high maintenance pain in the ass :D

**Comment by OJ** [comment]
The site you mentioned doesn't do any redirects, it just returns the main page content:
```
➜  ~  curl -I http://www.whoismrrobot.com/
HTTP/1.1 200 OK
Server: Apache
X-Powered-By: PHP/5.4.13
Content-Type: text/html
Cache-Control: max-age=5
Date: Sat, 01 Aug 2015 20:51:47 GMT
Connection: keep-alive

➜  ~  curl -I http://www.whoismrrobot.com/doesnotexist
HTTP/1.1 200 OK
Server: Apache
X-Powered-By: PHP/5.4.13
Content-Type: text/html
Content-Length: 0
Cache-Control: max-age=5
Date: Sat, 01 Aug 2015 20:51:54 GMT
Connection: keep-alive
Set-Cookie: pers_cookie_insert_app.usanetwork=560378584.20480.0000; expires=Sun, 02-Aug-2015 00:51:54 GMT; path=/
```

So, works as designed! Future enhancements will sort this out. Cheers!

**Comment by josephwhenry** [comment]
Any chance these issues are being worked on? I still encounter this problem frequently.
